HAI 1.2
    BTW THIS IS A COMMENT SO IT WON'T DO SHIT
    CAN HAS STDIO?
    I HAS A APPLE ITZ 2
    I HAS A PEAR ITZ 7
    VISIBLE APPLE
    APPLE R 5
    VISIBLE APPLE
    VISIBLE "LOOOOP"
    IM IN YR LOOP NERFIN YR PEAR TIL 0
        VISIBLE PEAR
        VISIBLE "WE STILL IN THE LOOP"
    IM OUTTA YR LOOP
    BOTH SAEM 5 AN 9, O RLY?
        YA RLY
            VISIBLE "5 REALLY IS 9"
        NO WAI
            VISIBLE "5 ISNT 9"
        OIC
KTHXBYE